# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-team-roles
  description: This component is responsible for provisioning user and system IAM roles outside the `identity` account
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







